# 이메일 설정
spring:
  mail:
      host: smtp.gmail.com
      port: 587
      username: dahoonemailtest@gmail.com
      password: andrprnfma
      properties:
        mail:
            transport:
              protocol: smtp
            smtp:
                ssl:
                    protocols: TLSv1.2
                auth: true
                starttls:
                    enable: true
server:
  port: 8081